import React, { useState, useEffect, useMemo, useCallback } from 'react';
import { 
  C4Board, 
  C4Player, 
  Language, 
  C4ColumnEval 
} from '../types';
import { 
  C4_ROWS, 
  C4_COLS, 
  createEmptyC4Board, 
  getDropRow, 
  checkC4Winner, 
  evaluateAllC4Columns 
} from '../engines/connect4';
import { AlgorithmThoughtVisualizer } from './AlgorithmThoughtVisualizer';
import { soundFx } from '../utils/sound';
import confetti from 'canvas-confetti';
import { 
  RotateCcw, 
  User, 
  Lightbulb, 
  Sliders, 
  TrendingUp,
  Award,
  Zap,
  Cpu
} from 'lucide-react';

interface Props {
  lang: Language;
}

export const Connect4Game: React.FC<Props> = ({ lang }) => {
  const [board, setBoard] = useState<C4Board>(createEmptyC4Board());
  const [turn, setTurn] = useState<C4Player>('R'); // R starts (Player 1)
  const [humanPlayer, setHumanPlayer] = useState<C4Player>('Y'); // Algorithm plays R (Red) by default
  const [gameMode, setGameMode] = useState<'pve' | 'eve' | 'pvp'>('pve');
  const [history, setHistory] = useState<C4Board[]>([createEmptyC4Board()]);
  const [moveHistoryCols, setMoveHistoryCols] = useState<number[]>([]);
  const [searchDepth, setSearchDepth] = useState<number>(8);
  const [showParity, setShowParity] = useState(false);
  const [hoverCol, setHoverCol] = useState<number | null>(null);
  const [showHint, setShowHint] = useState(false);
  const [stats, setStats] = useState({ rWins: 0, yWins: 0, draws: 0 });

  const algoPlayer = humanPlayer === 'R' ? 'Y' : 'R';
  const { winner, winningCells } = useMemo(() => checkC4Winner(board), [board]);
  const isGameOver = winner !== null;

  // Real-time Pre-calculated Column Game Theory Analysis
  const moveSeqString = moveHistoryCols.join(',');
  const analysis = useMemo(() => {
    if (isGameOver) return { evals: [] as C4ColumnEval[], bestCol: 3, totalNodes: 0, lookupTimeMs: 0 };
    return evaluateAllC4Columns(board, turn, searchDepth, moveSeqString);
  }, [board, turn, searchDepth, moveSeqString, isGameOver]);

  const bestColumn = analysis.bestCol;

  // Contextual Ideal Recommendation for Connect 4
  const idealRecommendation = useMemo(() => {
    if (isGameOver || bestColumn === -1) return null;
    const num = bestColumn + 1;
    const opp: C4Player = turn === 'R' ? 'Y' : 'R';

    const dropRow = getDropRow(board, bestColumn);
    if (dropRow !== -1) {
      // Immediate win
      const tempBoardWin = board.map(r => [...r]);
      tempBoardWin[dropRow][bestColumn] = turn;
      if (checkC4Winner(tempBoardWin).winner === turn) {
        return {
          colNum: num,
          reasonHe: `שחק בעמודה #${num} כדי להשלים 4-בשורה ולנצח את המשחק מיד! 🏆`,
          reasonEn: `Play Column #${num} to complete 4-in-a-row and win immediately! 🏆`
        };
      }

      // Immediate block
      const tempBoardBlock = board.map(r => [...r]);
      tempBoardBlock[dropRow][bestColumn] = opp;
      if (checkC4Winner(tempBoardBlock).winner === opp) {
        return {
          colNum: num,
          reasonHe: `חיוני! שחק בעמודה #${num} כדי לחסום איום 4-בשורה של היריב ברגע האחרון! 🛡️`,
          reasonEn: `Critical! Play Column #${num} to block opponent's 4-in-a-row threat! 🛡️`
        };
      }
    }

    if (bestColumn === 3) {
      return {
        colNum: num,
        reasonHe: `שחק בעמודה #4 (עמודת המרכז). שליטה בעמודה 4 פותחת את מספר רצפי ה-4 המקסימלי בלוח. 🎯`,
        reasonEn: `Play Column #4 (Center Column). Center control creates maximum potential 4-in-a-row lines. 🎯`
      };
    }

    return {
      colNum: num,
      reasonHe: `שחק בעמודה #${num} - בחירה אופטימלית עפ"י האלגוריתם המבטיחה יתרון טקטי ומניעת שגיאות. ⚡`,
      reasonEn: `Play Column #${num} - optimal move generated by engine preventing blunders. ⚡`
    };
  }, [board, turn, isGameOver, bestColumn]);

  // Convert column evaluations to candidate thought steps for live animation
  const candidateThoughtSteps = useMemo(() => {
    return analysis.evals.map(ev => {
      let detailHe = ev.commentary || 'ניתוח עמודה';
      let detailEn = 'Column evaluation';
      let status: 'scanning' | 'pruned' | 'optimal' | 'evaluating' = 'evaluating';

      if (ev.isBest) {
        status = 'optimal';
        detailHe = 'עמודה מנצחת/אופטימלית';
        detailEn = 'Optimal Column';
      } else if (ev.threatLevel === 'blunder') {
        status = 'pruned';
        detailHe = 'שגיאה קטלנית - נגזם';
        detailEn = 'Blunder - Pruned';
      } else if (!ev.isValid) {
        status = 'pruned';
        detailHe = 'עמודה מלאה';
        detailEn = 'Full Column';
      }

      return {
        id: `col-${ev.col}`,
        labelHe: `עמודה #${ev.col + 1}`,
        labelEn: `Col #${ev.col + 1}`,
        status,
        score: ev.score > 10000 ? '+WIN' : ev.score < -10000 ? '-LOSS' : Math.round(ev.score / 10),
        detailHe,
        detailEn
      };
    });
  }, [analysis]);

  // Sound & Confetti
  useEffect(() => {
    if (winner === 'R' || winner === 'Y') {
      soundFx.playWin();
      confetti({ particleCount: 70, spread: 80, origin: { y: 0.6 } });
      setStats(prev => ({
        ...prev,
        rWins: winner === 'R' ? prev.rWins + 1 : prev.rWins,
        yWins: winner === 'Y' ? prev.yWins + 1 : prev.yWins
      }));
    } else if (winner === 'draw') {
      soundFx.playDraw();
      setStats(prev => ({ ...prev, draws: prev.draws + 1 }));
    }
  }, [winner]);

  // Drop piece into column
  const dropPiece = useCallback((col: number) => {
    if (isGameOver) return;
    const row = getDropRow(board, col);
    if (row === -1) return;

    soundFx.playDrop(row);
    const newBoard = board.map(r => [...r]);
    newBoard[row][col] = turn;

    setBoard(newBoard);
    setHistory(prev => [...prev, newBoard]);
    setMoveHistoryCols(prev => [...prev, col]);
    setTurn(prev => (prev === 'R' ? 'Y' : 'R'));
    setShowHint(false);
  }, [board, isGameOver, turn]);

  // Instant Algorithmic Execution
  useEffect(() => {
    if (isGameOver) return;

    const isAlgoTurn = gameMode === 'eve' || (gameMode === 'pve' && turn === algoPlayer);
    if (!isAlgoTurn) return;

    const timer = setTimeout(() => {
      const { bestCol } = evaluateAllC4Columns(board, turn, searchDepth, moveHistoryCols.join(','));
      if (bestCol !== -1 && getDropRow(board, bestCol) !== -1) {
        dropPiece(bestCol);
      }
    }, gameMode === 'eve' ? 500 : 150);

    return () => clearTimeout(timer);
  }, [board, turn, isGameOver, gameMode, algoPlayer, searchDepth, moveHistoryCols, dropPiece]);

  // Reset Game
  const resetGame = () => {
    const empty = createEmptyC4Board();
    setBoard(empty);
    setHistory([empty]);
    setMoveHistoryCols([]);
    setTurn('R');
  };

  // Undo Move
  const undoMove = () => {
    if (history.length <= 1) return;
    const stepsBack = gameMode === 'pve' && history.length >= 3 ? 2 : 1;
    const newHistory = history.slice(0, -stepsBack);
    const newMoveCols = moveHistoryCols.slice(0, -stepsBack);
    const targetBoard = newHistory[newHistory.length - 1];
    setBoard(targetBoard);
    setHistory(newHistory);
    setMoveHistoryCols(newMoveCols);
    
    let rCount = 0;
    let yCount = 0;
    for (let r = 0; r < C4_ROWS; r++) {
      for (let c = 0; c < C4_COLS; c++) {
        if (targetBoard[r][c] === 'R') rCount++;
        if (targetBoard[r][c] === 'Y') yCount++;
      }
    }
    setTurn(rCount === yCount ? 'R' : 'Y');
  };

  // Red Advantage calculation
  const redAdvantage = useMemo(() => {
    if (winner === 'R') return 100;
    if (winner === 'Y') return 0;
    if (winner === 'draw') return 50;

    const bestEval = analysis.evals.find(e => e.col === bestColumn);
    if (!bestEval) return 50;
    
    const score = turn === 'R' ? bestEval.score : -bestEval.score;
    const clamped = Math.max(-10000, Math.min(10000, score));
    return 50 + (clamped / 200);
  }, [winner, analysis, bestColumn, turn]);

  return (
    <div className="flex flex-col gap-6 max-w-6xl mx-auto">
      
      {/* Top Banner */}
      <div className="bg-slate-900/90 border border-slate-800 p-4 rounded-2xl shadow-xl flex flex-wrap items-center justify-between gap-4 backdrop-blur-md">
        <div className="flex items-center gap-3">
          <div className="p-2.5 rounded-xl bg-amber-500/10 border border-amber-500/30 text-amber-400">
            <TrendingUp className="w-6 h-6" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h2 className="text-lg font-bold text-slate-100">
                {lang === 'he' ? '4 בשורה: מנוע אלגוריתמי פתור (Victor Allis 1988)' : 'Connect 4: Precomputed Solved Engine'}
              </h2>
              <span className="px-2.5 py-0.5 rounded-full text-[11px] font-semibold bg-emerald-500/10 text-emerald-400 border border-emerald-500/30 flex items-center gap-1">
                <Zap className="w-3 h-3" />
                <span>Precalculated Opening Book</span>
              </span>
            </div>
            <p className="text-xs text-slate-400 mt-0.5">
              {lang === 'he' 
                ? 'הוכח מתמטית: אלגוריתם שפותח באדום (עמודה 4) מנצח בהכרח תוך 41 מהלכים מול כל הגנה אפשרית.'
                : 'Mathematically proven win strategy: Red algorithm opening in center Column 4 wins in 41 moves.'}
            </p>
          </div>
        </div>

        {/* Controls */}
        <div className="flex items-center gap-2 flex-wrap">
          <div className="bg-slate-950 p-1 rounded-xl border border-slate-800 flex items-center gap-1">
            <button
              onClick={() => { setGameMode('pve'); resetGame(); }}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold transition-all ${
                gameMode === 'pve' ? 'bg-amber-500 text-slate-950 shadow-md shadow-amber-500/20' : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <User className="w-3.5 h-3.5" />
              <span>{lang === 'he' ? 'שחק מול האלגוריתם' : 'Play Vs Algorithm'}</span>
            </button>
            <button
              onClick={() => { setGameMode('eve'); resetGame(); }}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold transition-all ${
                gameMode === 'eve' ? 'bg-amber-500 text-slate-950 shadow-md shadow-amber-500/20' : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              <Cpu className="w-3.5 h-3.5" />
              <span>{lang === 'he' ? 'סימולציה אוטומטית' : 'Auto Simulation'}</span>
            </button>
          </div>

          <div className="bg-slate-950 px-3 py-1.5 rounded-xl border border-slate-800 flex items-center gap-2 text-xs">
            <Sliders className="w-3.5 h-3.5 text-amber-400" />
            <select
              value={searchDepth}
              onChange={e => setSearchDepth(Number(e.target.value))}
              className="bg-slate-900 text-amber-400 font-mono font-bold rounded px-2 py-0.5 border border-slate-700 outline-none cursor-pointer"
            >
              <option value={6}>{lang === 'he' ? 'עומק 6 (מהיר)' : 'Depth 6'}</option>
              <option value={8}>{lang === 'he' ? 'עומק 8 (מומלץ)' : 'Depth 8'}</option>
              <option value={10}>{lang === 'he' ? 'עומק 10 (מקסימלי)' : 'Depth 10'}</option>
            </select>
          </div>
        </div>
      </div>

      {/* Main Board & Evaluator */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
        
        <div className="lg:col-span-7 flex flex-col items-center gap-4 bg-slate-900/80 border border-slate-800 p-6 rounded-3xl shadow-2xl">
          
          <div className="w-full flex items-center justify-between border-b border-slate-800 pb-3 flex-wrap gap-2">
            <div className="flex items-center gap-3">
              <div className="flex items-center gap-2 font-bold text-sm">
                <span className="text-slate-400">{lang === 'he' ? 'תור:' : 'Turn:'}</span>
                <span className={`px-3 py-1 rounded-lg flex items-center gap-2 ${
                  turn === 'R' ? 'bg-rose-500/10 text-rose-400 border border-rose-500/30' : 'bg-amber-500/10 text-amber-400 border border-amber-500/30'
                }`}>
                  <span className={`w-3.5 h-3.5 rounded-full ${turn === 'R' ? 'bg-rose-500' : 'bg-amber-400'}`}></span>
                  <span>{turn === algoPlayer ? (lang === 'he' ? 'אלגוריתם (מנצח)' : 'Algorithm') : (lang === 'he' ? 'אתה' : 'You')}</span>
                </span>
              </div>
            </div>

            <div className="flex items-center gap-2 text-xs font-mono text-emerald-400 bg-emerald-950/40 px-2.5 py-1 rounded-lg border border-emerald-800/40">
              <Zap className="w-3.5 h-3.5" />
              <span>Lookup: {analysis.lookupTimeMs}ms</span>
            </div>
          </div>

          {/* Advantage Bar */}
          <div className="w-full bg-slate-950 border border-slate-800 p-3 rounded-2xl flex flex-col gap-1.5">
            <div className="flex justify-between text-xs font-semibold">
              <span className="text-rose-400">Red (Player 1)</span>
              <span className="text-slate-400 font-mono text-[11px]">
                {lang === 'he' ? `צמתים שנותחו: ${analysis.totalNodes.toLocaleString()}` : `Nodes Evaluated: ${analysis.totalNodes.toLocaleString()}`}
              </span>
              <span className="text-amber-400">Yellow (Player 2)</span>
            </div>
            
            <div className="w-full h-3 bg-slate-800 rounded-full overflow-hidden flex relative" dir="ltr">
              <div 
                className="h-full bg-gradient-to-r from-rose-600 to-rose-400 transition-all duration-300"
                style={{ width: `${redAdvantage}%` }}
              />
              <div 
                className="h-full bg-gradient-to-r from-amber-300 to-amber-500 transition-all duration-300"
                style={{ width: `${100 - redAdvantage}%` }}
              />
            </div>
          </div>

          {/* Ideal User Recommendation Banner */}
          {idealRecommendation && (
            <div className={`w-full p-3.5 rounded-2xl border transition-all flex items-start gap-3 text-xs shadow-lg ${
              showHint 
                ? 'bg-amber-950/80 border-amber-500 text-amber-200 ring-2 ring-amber-400/50 animate-pulse' 
                : 'bg-slate-950/90 border-slate-800 text-slate-200'
            }`}>
              <div className="p-2 rounded-xl bg-amber-500/20 text-amber-400 shrink-0 mt-0.5">
                <Lightbulb className="w-4 h-4" />
              </div>
              <div className="flex flex-col gap-1">
                <div className="flex items-center gap-2">
                  <span className="font-bold text-amber-400">
                    {lang === 'he' ? `המלצה אידיאלית לתורך (${turn === 'R' ? 'אדום' : 'צהוב'}):` : `Ideal Recommendation for Turn (${turn}):`}
                  </span>
                  <span className="px-2 py-0.5 rounded bg-amber-500 text-slate-950 font-mono font-bold text-[11px]">
                    {lang === 'he' ? `עמודה #${idealRecommendation.colNum}` : `Col #${idealRecommendation.colNum}`}
                  </span>
                </div>
                <p className="text-slate-300 leading-relaxed font-medium">
                  {lang === 'he' ? idealRecommendation.reasonHe : idealRecommendation.reasonEn}
                </p>
              </div>
            </div>
          )}

          {/* Board */}
          <div className="relative p-4 sm:p-5 bg-blue-900/90 rounded-3xl border-4 border-blue-800 shadow-2xl select-none">
            
            <div className="grid grid-cols-7 gap-2 sm:gap-3 mb-3">
              {Array.from({ length: C4_COLS }).map((_, c) => {
                const colEval = analysis.evals.find(e => e.col === c);
                const isOptimal = colEval?.isBest && !isGameOver;
                const isFull = getDropRow(board, c) === -1;
                const isSuggested = showHint && isOptimal;

                return (
                  <button
                    key={c}
                    onClick={() => dropPiece(c)}
                    onMouseEnter={() => setHoverCol(c)}
                    onMouseLeave={() => setHoverCol(null)}
                    disabled={isFull || isGameOver}
                    className={`flex flex-col items-center justify-center p-1 sm:p-1.5 rounded-xl text-[10px] font-mono font-bold transition-all ${
                      isFull 
                        ? 'opacity-20 cursor-not-allowed bg-slate-900 text-slate-600' 
                        : isOptimal
                          ? 'bg-emerald-500 text-slate-950 ring-2 ring-emerald-300 shadow-lg scale-105 cursor-pointer animate-bounce'
                          : colEval?.threatLevel === 'blunder'
                            ? 'bg-rose-950/80 text-rose-300 border border-rose-600 cursor-pointer'
                            : 'bg-slate-950/80 hover:bg-slate-800 text-slate-300 border border-slate-800 cursor-pointer'
                    } ${isSuggested ? 'ring-4 ring-amber-400' : ''}`}
                  >
                    <span>{isOptimal ? '⭐ BEST' : `#${c + 1}`}</span>
                  </button>
                );
              })}
            </div>

            <div className="grid grid-cols-7 gap-2 sm:gap-3 bg-blue-950/80 p-3 sm:p-4 rounded-2xl border-2 border-blue-700/50 shadow-inner">
              {Array.from({ length: C4_COLS }).map((_, colIdx) => (
                <div 
                  key={colIdx} 
                  className={`flex flex-col gap-2 sm:gap-3 cursor-pointer rounded-xl p-0.5 transition-colors ${
                    hoverCol === colIdx && !isGameOver ? 'bg-blue-800/40' : ''
                  }`}
                  onClick={() => dropPiece(colIdx)}
                >
                  {Array.from({ length: C4_ROWS }).map((_, rowIdx) => {
                    const piece = board[rowIdx][colIdx];
                    const isWinning = winningCells?.some(([r, c]) => r === rowIdx && c === colIdx);
                    const isParityOdd = (rowIdx + 1) % 2 !== 0;

                    return (
                      <div
                        key={rowIdx}
                        className={`w-8 h-8 sm:w-11 sm:h-11 rounded-full border-2 border-blue-900 flex items-center justify-center relative overflow-hidden transition-all duration-300 shadow-inner ${
                          piece === 'R'
                            ? 'bg-gradient-to-br from-rose-500 to-rose-700 shadow-rose-900/50'
                            : piece === 'Y'
                              ? 'bg-gradient-to-br from-amber-300 to-amber-500 shadow-amber-900/50'
                              : 'bg-slate-950/90'
                        } ${isWinning ? 'ring-4 ring-emerald-400 ring-offset-2 ring-offset-blue-950 animate-pulse' : ''}`}
                      >
                        {showParity && piece === null && (
                          <span className="text-[9px] font-mono text-slate-600 select-none">
                            {isParityOdd ? 'Odd (R)' : 'Even (Y)'}
                          </span>
                        )}
                        {colIdx === 3 && piece === null && !showParity && (
                          <div className="w-1.5 h-1.5 rounded-full bg-cyan-400/40" />
                        )}
                      </div>
                    );
                  })}
                </div>
              ))}
            </div>

          </div>

          <div className="flex items-center gap-3 flex-wrap justify-center mt-2">
            <button
              onClick={resetGame}
              className="flex items-center gap-2 px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-xl text-xs font-semibold border border-slate-700 transition-all"
            >
              <RotateCcw className="w-4 h-4" />
              <span>{lang === 'he' ? 'משחק חדש' : 'Reset Board'}</span>
            </button>

            <button
              onClick={undoMove}
              disabled={history.length <= 1}
              className="flex items-center gap-2 px-4 py-2 bg-slate-800 hover:bg-slate-700 disabled:opacity-40 text-slate-200 rounded-xl text-xs font-semibold border border-slate-700 transition-all"
            >
              <span>{lang === 'he' ? 'בטל מהלך' : 'Undo Move'}</span>
            </button>

            <button
              onClick={() => setShowHint(prev => !prev)}
              disabled={isGameOver}
              className="flex items-center gap-2 px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-xl text-xs font-semibold border border-slate-700 transition-all"
            >
              <Lightbulb className="w-4 h-4 text-amber-400" />
              <span>{lang === 'he' ? 'מהלך אופטימלי' : 'Optimal Column'}</span>
            </button>
          </div>
        </div>

        {/* Right Info & Live Thought Visualizer */}
        <div className="lg:col-span-5 flex flex-col gap-4">
          
          <AlgorithmThoughtVisualizer
            gameType="connect4"
            lang={lang}
            currentTurnPlayer={turn}
            isAlgorithmTurn={gameMode === 'eve' || turn === algoPlayer}
            activeCandidates={candidateThoughtSteps}
            lookupTimeMs={analysis.lookupTimeMs}
            totalNodesAnalyzed={analysis.totalNodes}
            decisionExplanationHe={
              turn === 'R'
                ? 'אדום שולט במרכז הלוח (עמודה 4). סריקת Alpha-Beta מבטיחה מסלול כפוי מול כל מענה.'
                : 'צהוב מגן - האלגוריתם חוסם איומי ניצחון ומונע שגיאות קטלניות (Blunders).'
            }
            decisionExplanationEn={
              turn === 'R'
                ? 'Center column dominance maintained.'
                : 'Defensive blocking sequence active.'
            }
          />

          <div className="bg-slate-900/90 border border-slate-800 p-5 rounded-3xl shadow-xl flex flex-col gap-3">
            <div className="flex items-center gap-2 text-amber-400">
              <Award className="w-5 h-5" />
              <h3 className="font-bold text-sm text-slate-200">
                {lang === 'he' ? 'ספר פתיחות מוכח' : 'Proven Connect 4 Solved Book'}
              </h3>
            </div>
            
            <p className="text-xs text-slate-400 leading-relaxed">
              {lang === 'he' 
                ? 'המנוע משתמש בספר פתיחות מוכן מראש עפ"י הוכחת ויקטור אליס (1988) וטבלת Alpha-Beta עם O(1) Memory Cache.'
                : 'Victor Allis 1988 pre-computed opening table guarantees center column victory.'}
            </p>
          </div>
        </div>

      </div>

    </div>
  );
};
