import { EnvironmentConfig, EnvironmentPresetId } from '../types';

export const ENVIRONMENTS: Record<EnvironmentPresetId, EnvironmentConfig> = {
  tropical: {
    id: 'tropical',
    nameHe: 'לגונה טרופית',
    nameEn: 'Tropical Lagoon',
    descriptionHe: 'מי טורקיז קריסטליים, חול לבן ושמש טרופית בוהקת',
    descriptionEn: 'Crystal turquoise waters, white seabed sand and brilliant tropical sun',
    waterColorSurface: '#22d3ee',
    waterColorDeep: '#0e7490',
    floorType: 'sand_pebbles',
    sunElevation: 68,
    sunAzimuth: 135,
    sunColor: '#fffbeb',
    skyColorTop: '#38bdf8',
    skyColorHorizon: '#bae6fd',
    causticsIntensity: 1.5,
    bioluminescentGlow: false,
    ambientLight: 0.85,
    rainAllowed: true,
    defaultRainRate: 0
  },
  luxury_pool: {
    id: 'luxury_pool',
    nameHe: 'בריכת יוקרה',
    nameEn: 'Luxury Pool',
    descriptionHe: 'אריחי פסיפס כחולים, מים שקופים במיוחד וקאוסטיקה חדה',
    descriptionEn: 'Blue mosaic ceramic tiles, ultra-clear water and sharp dancing caustics',
    waterColorSurface: '#38bdf8',
    waterColorDeep: '#0284c7',
    floorType: 'blue_tiles',
    sunElevation: 75,
    sunAzimuth: 180,
    sunColor: '#ffffff',
    skyColorTop: '#60a5fa',
    skyColorHorizon: '#bfdbfe',
    causticsIntensity: 1.8,
    bioluminescentGlow: false,
    ambientLight: 0.9,
    rainAllowed: true,
    defaultRainRate: 0
  },
  sunset: {
    id: 'sunset',
    nameHe: 'שקיעה באוקיינוס',
    nameEn: 'Ocean Sunset',
    descriptionHe: 'שביל זהוב של שמש שוקעת, השתקפויות דרמטיות וגלים רגועים',
    descriptionEn: 'Golden sun reflection path, dramatic sky gradients and calm swell',
    waterColorSurface: '#fb923c',
    waterColorDeep: '#9a3412',
    floorType: 'ocean_rock',
    sunElevation: 18,
    sunAzimuth: 240,
    sunColor: '#f97316',
    skyColorTop: '#4c1d95',
    skyColorHorizon: '#fb923c',
    causticsIntensity: 0.7,
    bioluminescentGlow: false,
    ambientLight: 0.6,
    rainAllowed: true,
    defaultRainRate: 0
  },
  bioluminescence: {
    id: 'bioluminescence',
    nameHe: 'ביולומיננסנציה לילית',
    nameEn: 'Midnight Bioluminescence',
    descriptionHe: 'מים אפלים הזוהרים בכחול-חשמלי בעת תנועה, לאור ירח מלא',
    descriptionEn: 'Deep dark ocean with electric cyan glow ripples, starry sky and moonlight',
    waterColorSurface: '#06b6d4',
    waterColorDeep: '#020617',
    floorType: 'deep_chasm',
    sunElevation: 60,
    sunAzimuth: 45,
    sunColor: '#93c5fd', // Moonlight
    skyColorTop: '#020617',
    skyColorHorizon: '#0f172a',
    causticsIntensity: 0.9,
    bioluminescentGlow: true,
    ambientLight: 0.35,
    rainAllowed: true,
    defaultRainRate: 0
  },
  storm: {
    id: 'storm',
    nameHe: 'סערה ימית',
    nameEn: 'Stormy Sea',
    descriptionHe: 'גשם סוחף, עננים כבדים, גלים חדים וקצף לבן בראשי הגלים',
    descriptionEn: 'Heavy rain, dark stormy sky, sharp waves with whitecap foam',
    waterColorSurface: '#475569',
    waterColorDeep: '#1e293b',
    floorType: 'ocean_rock',
    sunElevation: 40,
    sunAzimuth: 90,
    sunColor: '#94a3b8',
    skyColorTop: '#1e293b',
    skyColorHorizon: '#475569',
    causticsIntensity: 0.4,
    bioluminescentGlow: false,
    ambientLight: 0.45,
    rainAllowed: true,
    defaultRainRate: 45
  }
};
